[package]
name = "turbo-crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turborepo-lib = { git = "https://github.com/vercel/turborepo.git" }
